First version
adevinta/vulcan-local-action pull request #1
Opened 2022-12-01 09:27 UTC by jesusfcr

2022-12-01 13:40 UTC, manelmontilla approved these changes
Minor typos that can be addressed in future PRs

2022-12-01 13:40 UTC, manelmontilla commented on README.md
> +- Perform static analusis over the current repository. See  `scan-repo` option.
s/analusis/analysis

2022-12-01 13:40 UTC, manelmontilla commented on README.md
> +- Applies configs in `vulcan.yaml` if they exists in the root of the repo. See `local-config` and `use-local-config` options..
s/exists/exist
s/options../options. ?

2022-12-01 13:40 UTC, danfaizer requested changes
Added a couple of minor comments.
Great job mate!

2022-12-01 13:40 UTC, danfaizer commented on action.yaml
> +    description: Wether to scan the local repo path
/Wether/Whether

2022-12-01 13:40 UTC, danfaizer commented on action.yaml
> +  log-level:
Is possible to specify the default? (even as a comment)

2022-12-01 14:11 UTC, jesusfcr commented on README.md
> +- Perform static analusis over the current repository. See  `scan-repo` option.
Thanks

2022-12-01 14:16 UTC, jesusfcr commented on README.md
> +- Applies configs in `vulcan.yaml` if they exists in the root of the repo. See `local-config` and `use-local-config` options..
thanks

2022-12-01 14:19 UTC, jesusfcr commented on action.yaml
> +    description: Wether to scan the local repo path
thanks

2022-12-01 14:56 UTC, manelmontilla approved these changes
LGTM

2022-12-12 14:19 UTC, danfaizer approved these changes
Great work! :clap:

2022-12-12 14:23 UTC, merged